# parent image
FROM node:8.11.2-slim
LABEL maintainer="vincentlee@dengtacj.com"

# runtime
RUN cd /etc/apt \
    && echo "" > sources.list \
    && echo "deb http://mirrors.163.com/debian/ jessie main non-free contrib" >> sources.list \
    && echo "deb http://mirrors.163.com/debian/ jessie-updates main non-free contrib" >> sources.list \
    && echo "deb http://mirrors.163.com/debian/ jessie-backports main non-free contrib" >> sources.list \
    && echo "deb-src http://mirrors.163.com/debian/ jessie main non-free contrib" >> sources.list \
    && echo "deb-src http://mirrors.163.com/debian/ jessie-updates main non-free contrib" >> sources.list \
    && echo "deb-src http://mirrors.163.com/debian/ jessie-backports main non-free contrib" >> sources.list \
    && echo "deb http://mirrors.163.com/debian-security/ jessie/updates main non-free contrib" >> sources.list \
    && echo "deb-src http://mirrors.163.com/debian-security/ jessie/updates main non-free contrib" >> sources.list \
    && apt-get update \
    && apt-get install -y libaio1 \
    # && apt-get install -y build-essential \
    && apt-get install -y unzip

# prepare dirs
RUN mkdir -p /home/node/app \
    && mkdir -p /home/node/logs \
    && mkdir -p /opt/oracle

# add app sources
COPY . /home/node/app

# oracle instant client
RUN pwd \
    && cd /home/node/app/lib \
    && unzip instantclient-basiclite-linux.x64-12.2.0.1.0.zip && rm instantclient-basiclite-linux.x64-12.2.0.1.0.zip \
    && mv instantclient_12_2 instantclient && mv instantclient /opt/oracle \
    && cd /opt/oracle/instantclient \
    && ln -s libclntsh.so.12.1 libclntsh.so \
    && ln -s libocci.so.12.1 libocci.so \
    && echo /opt/oracle/instantclient > /etc/ld.so.conf.d/oracle-instantclient.conf && ldconfig

# env
ENV LD_LIBRARY_PATH="/opt/oracle/instantclient"

# pm2
RUN npm install pm2 -g

# app denpendencies
RUN pwd \
    && cd /home/node/app \
    && npm install oracledb --unsafe-perm=true --allow-root \
    && npm install

# run app
WORKDIR /home/node/app
EXPOSE 55552
CMD ["pm2", "start", "pm2.json", "--no-daemon"]
# CMD ["npm", "run", "prod"]